site:
  title: Integreatly Docs
  start_page: home::index

content:
  sources:
    - url: .
      branches: HEAD
    - url: https://github.com/finp/user-documentation.git
      branches: antora
    - url: https://github.com/finp/mobile-docs.git
      branches: antora
    - url: https://github.com/finp/enmasse.git
      start_path: documentation
      branches: antora
    - url: https://github.com/finp/syndesis.git
      start_path: doc
      branches: antora


ui:
  bundle:
    url: ./i8y-ui-bundle/build/ui-bundle.zip

urls:
  redirect_facility: disabled

output:
  dir: ./static
